# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                 Role for downloading the files from the BOM                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
# 04/14/2021  Morgan Deegan       Reviewed - Complete
#
# -------------------------------------+---------------------------------------8



# -------------------------------------+---------------------------------------8
#
# Description:  Validation for Prerequisites 
#
- name:   Check required variables are present and not empty
  assert:
    that:
      - "sapbits_location_base_path is defined"                                 # Has the variable been defined
      - "sapbits_location_base_path | trim | length != 0"                       #   and given a value

      - "sapbits_bom_files is defined"                                          # Has the variable been defined
      - "sapbits_bom_files | trim | length != 0"                                #   and given a value

      - "bom_base_name is defined"                                              # Has the variable been defined
      - "bom_base_name | trim | length != 0"                                    #   and given a value

      - "target_media_location is defined"                                      # Has the variable been defined
      - "target_media_location | trim | length != 0"                            #   and given a value
# -------------------------------------+---------------------------------------8




#----------------------------------------
# BEGIN - OLD CODE
#----------------------------------------

# - import_tasks: pre_checks.yaml

# Register BOM
- name:         "Register BOM: {{ bom_iterator }}"
  include_vars:
    file:       "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
    name:       bom

- include_tasks:  "iterate_bom.yaml"
  vars:
    bom_iterator: "{{ bom_base_name }}"

- include_tasks:  "iterate_bom.yaml"
  vars:
    bom_iterator: "{{ bom_dependency.name }}"
  loop:           "{{ bom.materials.dependencies | flatten(levels=1) }}"
    # loop_var:     bom_dependency
  when:           bom.materials.dependencies is defined
                  and (bom.materials.dependencies|length>0)
