# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                 Role for downloading the files from the BOM                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
# 04/14/2021  Morgan Deegan       Reviewed - Complete
#
# -------------------------------------+---------------------------------------8


- import_tasks:     pre_checks.yaml



# Register BOM
- name:             "Register BOM: {{ bom_base_name }}"
  include_vars:
    file:           "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
    name:           bom


# TODO:
#       Enhance so a single task loops over bas bom and dependencies

- include_tasks:    "bom_download.yaml"
  vars:
    bom_iterator:   "{{ bom_base_name }}"



- include_tasks:    "bom_download.yaml"
  vars:
    bom_iterator:   "{{ bom_dependency.name }}"
  loop:             "{{ bom.materials.dependencies | flatten(levels=1) }}"
  loop_control:
    loop_var:       bom_dependency
  when:             bom.materials.dependencies is defined
                    and (bom.materials.dependencies|length>0)

...
