# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                 Role for downloading the files from the BOM                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
# 04/14/2021  Morgan Deegan       Reviewed - Complete
#
# -------------------------------------+---------------------------------------8


- import_tasks:     pre_checks.yaml

# -------------------------------------+---------------------------------------8
#
# Description:  Download specified BOM and Register as a dictionary.
#
- name:         "Download Main BOM: {{ bom_base_name }}"
  get_url:
    url:        "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/{{ bom_base_name }}.yaml{{ sapbits_sas_token }}"
    dest:       "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
    mode:       0644
  register:     result
  until:        result is succeeded
  retries:      10
  delay:        6
  delegate_to:  localhost                                                         # Causes action to happen  on the Ansible Controller
  become:       no

- name:         "Register BOM: {{ bom_base_name }}"
  include_vars:
    file:       "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
    name:       bom
#------------------<DEBUGGING>-------------------
# - debug:  
#     msg:      "{{ item.archive }}"
#   loop:       "{{ bom.materials.media|flatten(levels=1) }}"
#
# - debug:  
#     msg:      "{{ item.name }}"
#   loop:       "{{ bom.materials.dependencies|flatten(levels=1) }}"
#------------------</DEBUGGING>------------------
# -------------------------------------+---------------------------------------8



# -------------------------------------+---------------------------------------8
#
# Description:  Download dependant BOM. Check the Main BOM for dependencies
#               under materials (materials.dependencies)
#
# Example:      materials:
#                 dependencies:
#                   - name:      HANA_2_00_055_v1
#
- name:         "Download Dependent BOM(s)"
  get_url:
    url:        "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ item.name }}/{{ item.name }}.yaml{{ sapbits_sas_token }}"
    dest:       "{{ inventory_dir }}/{{ item.name }}.yaml"
    mode:       0644
  register:     result
  until:        result is succeeded
  retries:      10
  delay:        6
  delegate_to:  localhost                                                         # Causes action to happen  on the Ansible Controller
  become:       no
  loop:         "{{ bom.materials.dependencies | flatten(levels=1) }}"
  when:             
    - bom.materials.dependencies is defined
    - bom.materials.dependencies|length>0
  # when:         bom.materials.dependencies is defined
  #               and (bom.materials.dependencies|length>0)
# -------------------------------------+---------------------------------------8



# # Register BOM
# - name:             "Register BOM: {{ bom_base_name }}"
#   include_vars:
#     file:           "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
#     name:           bom


# TODO:
#       Enhance so a single task loops over bas bom and dependencies

- include_tasks:    "bom_download.yaml"
  vars:
    bom_iterator:   "{{ bom_base_name }}"



- include_tasks:    "bom_download.yaml"
  vars:
    bom_iterator:   "{{ bom_dependency.name }}"
  loop:             "{{ bom.materials.dependencies | flatten(levels=1) }}"
  loop_control:
    loop_var:       bom_dependency
  when:             
    - bom.materials.dependencies is defined
    - bom.materials.dependencies|length>0
  # when:             bom.materials.dependencies is defined
  #                   and (bom.materials.dependencies|length>0)

...
