# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Role for downloading the BOM                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
# Description:  Download the specified BOM file to the ansible controller.
#               Download any dependent BOMs, as well.
#
#
# Objects:
#   External:
#             sapbits_location_base_path      - URL of Blob Storage
#             sapbits_bom_files               - path to the root of the sap file store
#             bom_base_name                   - Name of BOM
#             sapbits_sas_token               - SAS Token
#             inventory_dir                   - Path to the inventory location on the ansible controller
#
#   Internal:
#             result                          - objet to store the results of a task execution
#
#   Created:
#             bom                             - object containing the specified BOM
#
# -------------------------------------+---------------------------------------8
# Reviews:
#
# 04/14/2021  Morgan Deegan       Reviewed - Complete
#
# -------------------------------------+---------------------------------------8
---
# -------------------------------------+---------------------------------------8
#
# Description:  Validation for Prerequisites 
#
- name:   Check required variables are present and not empty
  assert:
    that:
      - "sapbits_location_base_path is defined"                                 # Has the variable been defined
      - "sapbits_location_base_path | trim | length != 0"                       #   and given a value

      - "sapbits_bom_files is defined"                                          # Has the variable been defined
      - "sapbits_bom_files | trim | length != 0"                                #   and given a value

      - "bom_base_name is defined"                                              # Has the variable been defined
      - "bom_base_name | trim | length != 0"                                    #   and given a value

      - "target_media_location is defined"                                      # Has the variable been defined
      - "target_media_location | trim | length != 0"                            #   and given a value
# -------------------------------------+---------------------------------------8



# -------------------------------------+---------------------------------------8
#
# Description:  Download specified BOM and Register as a dictionary.
#
- name:         "Download Main BOM: {{ bom_base_name }}"
  get_url:
    url:        "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/{{ bom_base_name }}.yaml{{ sapbits_sas_token }}"
    dest:       "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
    mode:       0644
  register:     result
  until:        result is succeeded
  retries:      10
  delay:        6
  delegate_to:  localhost                                                         # Causes action to happen  on the Ansible Controller
  become:       no

- name:         "Register BOM: {{ bom_base_name }}"
  include_vars:
    file:       "{{ inventory_dir }}/{{ bom_base_name }}.yaml"
    name:       bom
#------------------<DEBUGGING>-------------------
# - debug:  
#     msg:      "{{ item.archive }}"
#   loop:       "{{ bom.materials.media|flatten(levels=1) }}"
#
# - debug:  
#     msg:      "{{ item.name }}"
#   loop:       "{{ bom.materials.dependencies|flatten(levels=1) }}"
#------------------</DEBUGGING>------------------
# -------------------------------------+---------------------------------------8



# -------------------------------------+---------------------------------------8
#
# Description:  Download dependant BOM. Check the Main BOM for dependencies
#               under materials (materials.dependencies)
#
# Example:      materials:
#                 dependencies:
#                   - name:      HANA_2_00_055_v1
#
- name:         "Download Dependent BOM(s)"
  get_url:
    url:        "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ item.name }}/{{ item.name }}.yaml{{ sapbits_sas_token }}"
    dest:       "{{ inventory_dir }}/{{ item.name }}.yaml"
    mode:       0644
  register:     result
  until:        result is succeeded
  retries:      10
  delay:        6
  delegate_to:  localhost                                                         # Causes action to happen  on the Ansible Controller
  become:       no
  loop:         "{{ bom.materials.dependencies | flatten(levels=1) }}"
  when:         bom.materials.dependencies is defined
                and (bom.materials.dependencies|length>0)
# -------------------------------------+---------------------------------------8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
